### ISSUE TITLE
No Installation Information

### ISSUE THREAD

**Issue by IncasedDevelopment** [tedztar/mcstatusbot#107]
For new bot users, I recommend adding a documentation for piece of information on how to properly install the bot and use it.
Thankfully I know how to use bots, code them and install them but It will be helpful to lower experienced bot users.

Thanks,
IncasedDevelopment.

**Comment by RahulR100** [comment]
The bot setup should be entirely automatic. Simply invite it to the server, and it will take care of the rest. Command usage is documented in the readme and the `/help` command

**Comment by IncasedDevelopment** [comment]
You have understood me wrong.
I think it would be excellent for new users who don't entirely know what they are doing, need to have some documentation on self-hosting the bot etc.

Thanks,
IncasedDevelopment.

**Comment by thedjchi** [comment]
@IncasedDevelopment the bot is centrally-hosted, not self-hosted. To add the bot to your server, simply invite the bot using the link in the readme.
