### ISSUE TITLE
API says server is online, bot does not.

### ISSUE THREAD

**Issue by Pxrple** [tedztar/mcstatusbot#15]
Api: `{"status":"success","online":true,"motd":"A Minecraft Server","error":"","players":{"max":20,"now":0},"server":{"name":"Spigot 1.8.8","protocol":47},"last_online":"1560711318","last_updated":"1560711318","duration":189376256}`

Bot: https://gyazo.com/fdce47f47dca267a280484dd4ee4ecf4

**Comment by Huskydog9988** [comment]
The bot only displays what ever the API sends back. Try and make sure that the correct info was entered.

**Comment by tedztar** [comment]
Was this fixed or is it still and issue?

**Comment by Huskydog9988** [comment]
Its a PICNIC error so the best we can do id have them change their ip and port. 

Also side not the API runs on a 5 min delay so the server up-time and downtime varies by 5 min

**Comment by tedztar** [comment]
This should be resolved with V0.2, as that is the current "Dev" Branch.
