### ISSUE TITLE
How To Allow BungeeCord Support

### ISSUE THREAD

**Issue by truality-dev** [tedztar/mcstatusbot#17]
So I'm Working On A BungeeCord Server. It Can Show If Its Online, But Doesn't Show The Correct Player Count, Any Ways To Fix?

**Comment by tedztar** [comment]
In what way does it shows the incorrect number? If it is easier dm me on discord (tedztar#9999)

**Comment by RedbearPlayz** [comment]
ill add you on discord cause i dont really get to my emails that much

**Comment by johncsuti** [comment]
currently on hexacord it shows correct number of players but it will only show idle at 15/1000 player it will also go offline from time to time
