### ISSUE TITLE
Server status update speed improvement

### ISSUE THREAD

**Issue by itsmemac** [tedztar/mcstatusbot#20]
Am using the discord bot for a while but the status update with the server takes more time (3-5 minutes sometimes) due to mcapi cache time limitations

is it possible to use mcstatus?
I have been using this rainmeter skin for a while and discovered it to show status update really quick (5 seconds)
The app uses mcstatus
https://github.com/Dinnerbone/mcstatus

**Comment by tedztar** [comment]
The reason the bot takes 5 min to update is the current API it is using, there is a dev fork I have made called V0.2 that changes it so the bot pings the server directly, thus you can set an update time you want. it also adds some basic commands. if you dont want a command you can just delete the file in the "command" folder

**Comment by itsmemac** [comment]
tried v0.2 but it always defaulted to 25565 instead of set port in config file.

Tried editing /home/container/node_modules/mc-ping-updated/lib/ping.js
with the server ping, but it always returns back to 25565

**Comment by tedztar** [comment]
Ok that’s because the bot is passing mc ping the port, odd how it is not reading the config file tho. Is the port in quote marks in the config file if so, Can you try change the “setting.port” in mcping.js to the port number in quotes and see if that fixed it

**Comment by itsmemac** [comment]
> Ok that’s because the bot is passing mc ping the port, odd how it is not reading the config file tho. Is the port in quote marks in the config file if so, Can you try change the “setting.port” in mcping.js to the port number in quotes and see if that fixed it

trying it now. few minutes. Will update

**Comment by itsmemac** [comment]
Now it works good. Changing setting.port to 25500 worked as it should

**Comment by tedztar** [comment]
Sweet, I’ll look into why it does not work with the config file.
