### ISSUE TITLE
You should add a link to this GitHub and https://mcstatusbot.com/ from the bot

### ISSUE THREAD

**Issue by Happypig375** [tedztar/mcstatusbot#206]
Add here

![image](https://github.com/tedztar/mcstatusbot/assets/19922066/a897604f-fef8-4be9-a11b-2b1381e88f80)

**Comment by RahulR100** [comment]
This is a great idea! We will update the information on discord shortly.

**Comment by RahulR100** [comment]
This has now been complete and should be visible on the bot.
