### ISSUE TITLE
Commands not work

### ISSUE THREAD

**Issue by niqoar** [tedztar/mcstatusbot#22]
When I want to use any of the bot commands I receive the following error: https://pastebin.com/8KakAKYK

How can I solve that?

**Comment by SKy4R** [comment]
same isue

**Comment by tedztar** [comment]
Current comment fixed the issue

**Comment by niqoar** [comment]
The status command still does not work: https://pastebin.com/3bkPcN9s

**Comment by tedztar** [comment]
Just made some changes can you try now?

**Comment by niqoar** [comment]
This is the mistake he show now: https://pastebin.com/ur5xUnka

**Comment by DeeGeeTill** [comment]
Running the program for the first time, fresh installation etc.

!status
![image](https://user-images.githubusercontent.com/34075000/75183134-bf275600-5739-11ea-9f30-8c2f2f176348.png)

!help
![image](https://user-images.githubusercontent.com/34075000/75183204-ee3dc780-5739-11ea-86a1-b391219fa483.png)

Might possibly be the deprecated dependencies but can't really say for sure.

**Comment by DeeGeeTill** [comment]
Oh, h. Turns out the pull request for this repository actually solves the problem.

https://github.com/Huskydog9988/mcstatusbot/tree/V0.2

Nvm, lol.

**Comment by tedztar** [comment]
ok I think I fixed all the bugs.

**Comment by niqoar** [comment]
Is there a way to order this?

![Sin título](https://user-images.githubusercontent.com/17512644/78505569-bff4d400-774a-11ea-83e6-896bac3176c0.png)
