### ISSUE TITLE
Bot not responding any more

### ISSUE THREAD

**Issue by Ant001ne-dev** [tedztar/mcstatusbot#224]
Hi,
Since today, i'm not able to use the bot any more. The slash commands doesn't work and the voice channels are not updating.
Can you fix this ?
Thanks !

**Comment by RahulR100** [comment]
Hey! Thanks for flagging this. I restarted the server and the bot should be back up now. Will post a further updated once I have identified a cause for this outage.

**Comment by Ant001ne-dev** [comment]
Thanks, it's working now !
