### ISSUE TITLE
The application did not respond

### ISSUE THREAD

**Issue by Knabbiii** [tedztar/mcstatusbot#226]
Hi,
Since yesterday, I'm not able to use the bot anymore. 
The slash commands don't work, and the voice channels are not updating.
Error Message: "The application did not respond"

Is this my or your mistake?

Thanks in advance for the help!

**Comment by RahulR100** [comment]
Thanks for flagging this! Looks like a network issue on our end. I have restarted all services and the bot should be back up soon.

**Comment by FawenYo** [comment]
I think the error has been raised again. Is there any API or page for us to check the bot status?

**Comment by RahulR100** [comment]
I have restarted it, should be back up and running now. An API page is being built right now but I am super busy with job so that update has been pending for a bit. I'll let you know when its released.
