### ISSUE TITLE
The application did not respond

### ISSUE THREAD

**Issue by IcyZap** [tedztar/mcstatusbot#228]
When any command at all is ran I just get the error "The application did not respond"

![Screenshot 2024-09-27 192644](https://github.com/user-attachments/assets/706cbd00-6bfb-4330-bf27-8bdfe546e9bc)

**Comment by RahulR100** [comment]
Thanks for the heads up Im restarting the bot now!

**Comment by RahulR100** [comment]
Should be back up and running now!

**Comment by IcyZap** [comment]
It working Now, I really appreciate it!

**Comment by IcyZap** [comment]
It working Now, I really appreciate it!
