### ISSUE TITLE
Unable to do anything with my server

### ISSUE THREAD

**Issue by yosefkokee** [tedztar/mcstatusbot#232]
Whenever I try to monitor or get status of my server then it says "There was an error while executing this command! Please try again in a few minutes. If the problem persists, please open an issue on GitHub."

My server is a bedrock aternos server with no underscores in it's ip

The monitor command that I do is:
/monitor ip:[my server IP] platform:bedrock
I tried running the command with and without the port but it still didn't work

**Comment by yosefkokee** [comment]
Now it just responds to every command with "The application did not respond" instantly

**Comment by RahulR100** [comment]
Yup I am investigating the issue here. Looks like our database went offline for some reason. Should be back up in about 10 minutes.

**Comment by RahulR100** [comment]
Bot should be back up and running now! Apologies for the service interruption. Let me know if you see any more issues.

**Comment by yosefkokee** [comment]
It works well now, thanks for fixing it!
