### ISSUE TITLE
DiscordAPIError: Missing Permissions

### ISSUE THREAD

**Issue by freddie316** [tedztar/mcstatusbot#27]
this error occured when I ran /status on my discord server

  name: 'DiscordAPIError',
  message: 'Missing Permissions',
  path: '/api/v7/channels/545496078800257025/messages/696100448079183883',
  code: 50013,
  method: 'DELETE'

**Comment by niqoar** [comment]
You need the bot to have the permissions on the channel where the command is executed.

**Comment by freddie316** [comment]
I gave the bot permission to send messages and read messages when I created it, and it shouldn't need any special permissions to access the text channel it is being used in. What permission could I be missing?

**Comment by niqoar** [comment]
Also need the permission of "Attach Files"

**Comment by freddie316** [comment]
Should I just update the role on my server or do I need to update the bot on the discord developer site?

**Comment by niqoar** [comment]
Just edit the channel and add the permissions to the bot

**Comment by freddie316** [comment]
I gave the bot's role attach files, and updated the channel its used in to allow it to attach files and the error still appears.

**Comment by johncsuti** [comment]
Not all commands work even with Attach files permission

**Comment by freddie316** [comment]
> Not all commands work even with Attach files permission

Commands actually still work fine for me, but the error generates for each time a command is used.

**Comment by SpielefreakJ** [comment]
The Bot deletes the command-message.
It should disappear when you give the role or bot the Manage Messages permission.
