### ISSUE TITLE
Gives error.

### ISSUE THREAD

**Issue by A-Wolf1** [tedztar/mcstatusbot#31]
When I try to run it after I did the configuration I get the following error.
I am kinda new to all of this so if you need further info pleas ask.
![image](https://user-images.githubusercontent.com/64983234/81334666-626ae480-9074-11ea-803e-331a858ddb32.png)

**Comment by Huskydog9988** [comment]
You need to install node.js and run the bot using `node mcbot.js`

**Comment by tedztar** [comment]
Closed due to no response.
