### ISSUE TITLE
/status embed not working while multiple players are online 

### ISSUE THREAD

**Issue by rainbow-glitch** [tedztar/mcstatusbot#32]
**First of all i'm sorry for my bad English**

The embed looks wierd while multiple players are online?
I haven't seen anyone else having this error.
It might be due to me adding additional code but i have checked and nothing is interfiering.

If you are wondering this is how it looks [http://prntscr.com/sfxrec](url) 

And no, it does not give any error at all in the console.
Any help would be appreciated.
_Not sure do i need to put the entire code so if I do just ask._
If this is a stupid question **I'm sorry**.

**Comment by niqoar** [comment]
add this in status.js:
`const escape = require('markdown-escape');`

**Comment by rainbow-glitch** [comment]
**Thanks! Its fixed.**
Didn't think it would be something that simple _😶_ 
I wondered around and found out why it needs that part  ˘˘ˇˇ
`onlinePlayers = escape(onlinePlayers.sort().join(', ')).replace(/\u00A7[0-9A-FK-OR]|\\n/ig,'');`
Thank you once again. Have a nice day.
