### ISSUE TITLE
Is there any way to have the bot automatically post the server status in a channel.

### ISSUE THREAD

**Issue by jdp1018** [tedztar/mcstatusbot#33]
As opposed to manually running /status command i would like the bot to do it automatically in a specific channel i have for it. Thank you. PS: i'm a beginner who doesn't know anything about coding, but i can follow suggestions.

**Comment by rainbow-glitch** [comment]
Yes, It is possible                                           _(I'm also a beginner in coding so not sure)_

**Do you want the bot to edit the message changing the status or just the status command to run automatically on a set delay?**

I tried to do it myself but i couldn't.

You could try to make a script that will repeat this `https://pastebin.com/5001HB0E` part of the status.js script but change that part to do it in a specific channel with something like this 
```
  var guild = client.guilds.get(guildID);
  var channel = guild.channels.get(channelID);
```
to define the channel and guild. 

I think you could make the repeating using a function.

**I have no idea if this will help but hope it does!**

**Comment by jdp1018** [comment]
> Yes, It is possible _(I'm also a beginner in coding so not sure)_
> 
> **Do you want the bot to edit the message changing the status or just the status command to run automatically on a set delay?**
> 
> I tried to do it myself but i couldn't.
> 
> You could try to make a script that will repeat this `https://pastebin.com/5001HB0E` part of the status.js script but change that part to do it in a specific channel with something like this
> 
> ```
>   var guild = client.guilds.get(guildID);
>   var channel = guild.channels.get(channelID);
> ```
> 
> to define the channel and guild.
> 
> I think you could make the repeating using a function.
> 
> **I have no idea if this will help but hope it does!**

Thanks for your reply. Yes, either of those options would work, i do not have a preference. So, the status.js script is what i need to edit in order to do this? Thanks.

**Comment by Davethetechguy** [comment]
Hi have you managed to get any further with this as I would like to do the same thing as you,
Thanks, 
Dave

**Comment by tedztar** [comment]
This should not be to hard, ill work on getting some of the other bugs fixed, but will add this at some point.
