### ISSUE TITLE
Issues if using TCPShield

### ISSUE THREAD

**Issue by JuniorGamingTime** [tedztar/mcstatusbot#41]
This is the error i get:

[2:46:51 PM]: Ping: Error getting server status
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:213:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by tedztar** [comment]
Hi when does this error occur?
At startup? Or running a command?

thanks

**Comment by JuniorGamingTime** [comment]
This happens at start up. Sorry for the late response

**Comment by caiusto** [comment]
Having the same problem.
