### ISSUE TITLE
Servers on diffrent Ports

### ISSUE THREAD

**Issue by MacGynan** [tedztar/mcstatusbot#42]
If you have two or more servers use the same IP but on a diffrent port the bot cant tell between the servers. I have two servers using a domain name with the diffrence bewteen the two servers are diffrent ports. 

E.G. If I connect to one server the bot says both servers have a player on them even if one is offline and the other has players on it.

It would be nice if the bots had a way to tell by port not just by IP.

For added context, I am running two diffrent bot with two diffrent settings. One is on port 75 and other is on 65. And it is not Rcon confusing it because Rcon is not using either of those ports and it is disabled.

**Comment by tedztar** [comment]
Are you running a bungee server?

**Comment by MacGynan** [comment]
No, one is vanilla 1.16 and another is Forge (Direwolf20 1.16 to be exact).
