### ISSUE TITLE
/players do not work

### ISSUE THREAD

**Issue by Tuurkevg** [tedztar/mcstatusbot#43]
Respons bot:
An error occured while attempting to query the server.
Server may be offline or does not have query set up.
Activate query with enable-query in server.properties.
Error: 
timed out

After i Fix this the problem comes every time back.

**Comment by tedztar** [comment]
Hi,

how are you fixing this issue? And what happens before it comes back?

thanks,
Tim

**Comment by srgvg** [comment]
@Tuurkevg (my son ;-) ) meant implementing the suggested fix, enabling `enable-query: true`. After that, the same error persists.
