### ISSUE TITLE
[Request] /IP command to display server IP

### ISSUE THREAD

**Issue by goethenorris** [tedztar/mcstatusbot#46]
Would this be possible? I don't have a static IP, and can't get one from my ISP.
 
thanks

**Comment by SixthTitan** [comment]
Put this in mcbot.js and replace it with your server's ip address; you can also run a domain resolve whois lookup to get the actual IP of the machine that the bot is running on. But I did this for my community.

 function getIP() {
	client.on('message', message => {

	if (message.content === '!ip') {
		message.channel.send('Minecraft Server: <my server ip or domain name>');
	}
  });
}
