### ISSUE TITLE
Monitor shows server offline after a few minutes

### ISSUE THREAD

**Issue by Enohriel** [tedztar/mcstatusbot#60]
Hello,

Monitor shows correct status (Online and correct number of player), but after a few minutes, it just shows a wrong offline status.

I'm using the invited bot, on a forge 1.16.5 dedicated server.

**Comment by thedjchi** [comment]
Hi @Enohriel, would you be able to provide me with the server address so I can try to replicate the issue? My monitored servers are all currently working, so I wonder if this is a server-specific issue. I'm not entirely sure if Forge servers are supported, as I've only tested with vanilla servers. As far as I know, all post-1.8 servers should be supported (I'm using the default protocol number of 47, but I can try changing the protocol version number to match your server version and see if that fixes it).

**Comment by Enohriel** [comment]
For some reason, it works fine now.
I haven't change anything.
I'll keep you updated

**Comment by RahulR100** [comment]
Closing this for now. If an issues arises feel free to open a new issue thread.
