### ISSUE TITLE
Server shows offline when changing the category name?

### ISSUE THREAD

**Issue by ItsBootsy** [tedztar/mcstatusbot#64]
Is there a way to change the category name from that of the IP?

I use a DDNS and upon changing the category from the DDNS address to something more fitting (VaultHunters for example) it will register for 30 seconds or so and then show the status as Offline, is this because it HAS to have the ip as the Category name or?

**Comment by RahulR100** [comment]
Hmm.. this should not be will look into this.

**Comment by RahulR100** [comment]
So, right now it does need the IP as the category name. We are changing this with the introduction of nicknames which should come sometime later this month :)
